"""
Google Gemini LLM Provider for MCP-Sentinel AI Agent.
Uses the official google-genai SDK for server-side model interaction.
Complies with:
- Security Rule #1: Never trust the AI agent.
- Security Rule #5: Never expose credentials or secrets.
- Server-side only execution.
- LLM provider abstraction.
"""

import uuid
from typing import Any, Optional

from google import genai
from google.genai import errors as genai_errors
from google.genai import types

from mcp_sentinel.agent.providers.base import AgentMessage, LLMProvider, LLMResponse, ToolCall
from mcp_sentinel.config.settings import get_settings
from mcp_sentinel.security.audit_logger import log_security_event
from mcp_sentinel.security.correlation import get_request_id
from mcp_sentinel.security.exceptions import ConfigurationError


class GeminiProvider(LLMProvider):
    """
    Production-grade Gemini provider wrapping the official Google GenAI SDK.
    Discovers MCP tools and registers them dynamically as Function Declarations.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: Optional[str] = None,
    ):
        settings = get_settings()
        self._api_key = api_key or settings.GEMINI_API_KEY
        self._model_name = model_name or settings.GEMINI_MODEL
        self._client: Optional[genai.Client] = None

    def _get_client(self) -> genai.Client:
        if not self._api_key:
            raise ConfigurationError(
                safe_message="Gemini API key is not configured.",
                internal_details="GEMINI_API_KEY environment variable or setting is empty.",
            )
        if self._client is None:
            self._client = genai.Client(api_key=self._api_key)
        return self._client

    @staticmethod
    def _clean_schema_for_gemini(schema: Any) -> Any:
        """
        Cleans JSON schema generated by Pydantic/FastMCP for strict Gemini API compatibility.
        Strips unsupported keywords: additionalProperties, title, $defs, definitions, $schema.
        Simplifies anyOf with null into nullable=True.
        """
        if not isinstance(schema, dict):
            return schema

        cleaned: dict[str, Any] = {}
        for k, v in schema.items():
            if k in (
                "additionalProperties",
                "additional_properties",
                "$schema",
                "title",
                "$defs",
                "definitions",
            ):
                continue

            if k == "anyOf" and isinstance(v, list):
                non_null = [
                    item for item in v if isinstance(item, dict) and item.get("type") != "null"
                ]
                has_null = any(isinstance(item, dict) and item.get("type") == "null" for item in v)
                if len(non_null) == 1:
                    simplified = GeminiProvider._clean_schema_for_gemini(non_null[0])
                    if has_null and isinstance(simplified, dict):
                        simplified["nullable"] = True
                    cleaned.update(simplified)
                    continue
                else:
                    cleaned["anyOf"] = [GeminiProvider._clean_schema_for_gemini(item) for item in v]
                    continue

            if isinstance(v, dict):
                cleaned[k] = GeminiProvider._clean_schema_for_gemini(v)
            elif isinstance(v, list):
                cleaned[k] = [
                    GeminiProvider._clean_schema_for_gemini(item)
                    if isinstance(item, dict)
                    else item
                    for item in v
                ]
            else:
                cleaned[k] = v

        return cleaned

    def _convert_tools(self, tools: list[dict[str, Any]]) -> Optional[list[types.Tool]]:
        """Converts discovered MCP tool definitions to Gemini Tool specifications."""
        if not tools:
            return None

        function_declarations: list[types.FunctionDeclaration] = []
        for t in tools:
            schema = t.get("input_schema") or t.get("parameters") or {}
            cleaned_schema = self._clean_schema_for_gemini(schema)
            fd = types.FunctionDeclaration(
                name=t["name"],
                description=t.get("description", ""),
                parameters=cleaned_schema,
            )
            function_declarations.append(fd)

        return [types.Tool(function_declarations=function_declarations)]

    def _convert_messages(self, messages: list[Any]) -> list[types.Content]:
        """Converts unified AgentMessage history into Gemini Content objects."""
        contents: list[types.Content] = []

        for m in messages:
            role = getattr(m, "role", None) or (m.get("role") if isinstance(m, dict) else "user")
            content = getattr(m, "content", None) or (m.get("content") if isinstance(m, dict) else "")
            tool_calls = getattr(m, "tool_calls", None) or (m.get("tool_calls") if isinstance(m, dict) else [])
            name = getattr(m, "name", None) or (m.get("name") if isinstance(m, dict) else None)

            if role == "user":
                part = types.Part.from_text(text=content or "")
                contents.append(types.Content(role="user", parts=[part]))

            elif role in ("assistant", "model"):
                parts: list[types.Part] = []
                if content:
                    parts.append(types.Part.from_text(text=content))
                if tool_calls:
                    for tc in tool_calls:
                        tc_name = getattr(tc, "name", None) or (tc.get("name") if isinstance(tc, dict) else str(tc))
                        tc_args = getattr(tc, "args", None) or (tc.get("args") if isinstance(tc, dict) else {})
                        parts.append(types.Part.from_function_call(name=tc_name, args=tc_args))
                if parts:
                    contents.append(types.Content(role="model", parts=parts))

            elif role == "tool":
                # Function response returned to the model
                tool_name = name or "mcp_tool"
                response_data = {"result": content or ""}
                part = types.Part.from_function_response(name=tool_name, response=response_data)
                contents.append(types.Content(role="user", parts=[part]))

        return contents

    async def generate_response(
        self,
        messages: list[AgentMessage],
        tools: list[dict[str, Any]],
        system_instruction: Optional[str] = None,
    ) -> LLMResponse:
        """
        Calls the Gemini model with conversation history and available MCP tools.
        """
        import asyncio

        client = self._get_client()
        gemini_tools = self._convert_tools(tools)
        contents = self._convert_messages(messages)

        config = types.GenerateContentConfig(
            temperature=0.0,
            system_instruction=system_instruction,
            tools=gemini_tools,
        )

        try:
            response = await client.aio.models.generate_content(
                model=self._model_name,
                contents=contents,
                config=config,
            )
        except genai_errors.APIError as exc:
            err_msg = str(exc)
            status_code = getattr(exc, "code", None) or getattr(exc, "status_code", None)
            if "API_KEY_INVALID" in err_msg or (
                "INVALID_ARGUMENT" in err_msg and "key" in err_msg.lower()
            ):
                user_msg = "Authentication with AI service failed. Please check the configured Gemini API key."
                err_code = "INVALID_API_KEY"
            elif "RESOURCE_EXHAUSTED" in err_msg or status_code == 429:
                user_msg = "Gemini API rate limit or quota exceeded. Please try again shortly."
                err_code = "RATE_LIMIT_EXCEEDED"
            elif "UNAVAILABLE" in err_msg or status_code == 503:
                user_msg = (
                    "Gemini service is temporarily unavailable. Please retry in a few moments."
                )
                err_code = "SERVICE_UNAVAILABLE"
            else:
                user_msg = (
                    "Unable to complete the request because the AI service encountered an error."
                )
                err_code = "GEMINI_API_ERROR"

            log_security_event(
                event_type="GEMINI_API_ERROR",
                action="generate_content",
                decision="FAIL",
                risk_classification="HIGH",
                success=False,
                error_code=err_code,
                details={"model": self._model_name, "error_code": err_code},
                request_id=get_request_id(),
            )
            return LLMResponse(
                content=user_msg,
                finish_reason="error",
            )
        except (TimeoutError, asyncio.TimeoutError):
            log_security_event(
                event_type="GEMINI_TIMEOUT",
                action="generate_content",
                decision="FAIL",
                risk_classification="HIGH",
                success=False,
                error_code="TIMEOUT",
                details={"model": self._model_name},
                request_id=get_request_id(),
            )
            return LLMResponse(
                content="The request to the AI reasoning service timed out. Please try again.",
                finish_reason="error",
            )
        except Exception as exc:
            log_security_event(
                event_type="GEMINI_UNEXPECTED_ERROR",
                action="generate_content",
                decision="FAIL",
                risk_classification="HIGH",
                success=False,
                error_code="GEMINI_EXCEPTION",
                details={"model": self._model_name, "error_type": type(exc).__name__},
                request_id=get_request_id(),
            )
            return LLMResponse(
                content="An error occurred while communicating with the reasoning service.",
                finish_reason="error",
            )

        # Parse response candidates
        if not response.candidates:
            return LLMResponse(content="No response generated.", finish_reason="stop")

        candidate = response.candidates[0]
        text_parts: list[str] = []
        tool_calls: list[ToolCall] = []

        if candidate.content and candidate.content.parts:
            for part in candidate.content.parts:
                if part.text:
                    text_parts.append(part.text)
                if part.function_call:
                    fc = part.function_call
                    call_id = f"call_{uuid.uuid4().hex[:8]}"
                    tool_calls.append(
                        ToolCall(
                            id=call_id,
                            name=fc.name,
                            args=dict(fc.args) if fc.args else {},
                        )
                    )

        combined_text = "".join(text_parts).strip() if text_parts else None

        usage_info = None
        if hasattr(response, "usage_metadata") and response.usage_metadata:
            usage_info = {
                "prompt_token_count": getattr(response.usage_metadata, "prompt_token_count", None),
                "candidates_token_count": getattr(
                    response.usage_metadata, "candidates_token_count", None
                ),
            }

        return LLMResponse(
            content=combined_text,
            tool_calls=tool_calls,
            finish_reason=str(candidate.finish_reason) if candidate.finish_reason else "stop",
            usage=usage_info,
        )
