"""
Trusted Tool Risk Registry and Scoring Factors for MCP-Sentinel Phase 4.
The server is authoritative: tool profiles and factor weights are strictly controlled server-side.
"""

from typing import Optional

from mcp_sentinel.security.risk.models import DataSensitivityEnum, ToolRiskProfile

# Scoring weights
DESTRUCTIVE_FACTOR_WEIGHT: int = 25
EXTERNAL_SIDE_EFFECT_WEIGHT: int = 10

DATA_SENSITIVITY_WEIGHTS: dict[DataSensitivityEnum, int] = {
    DataSensitivityEnum.PUBLIC: 0,
    DataSensitivityEnum.INTERNAL: 5,
    DataSensitivityEnum.CONFIDENTIAL: 5,
    DataSensitivityEnum.SENSITIVE: 10,
    DataSensitivityEnum.RESTRICTED: 25,
}

ENVIRONMENT_WEIGHTS: dict[str, int] = {
    "development": 0,
    "test": 0,
    "staging": 10,
    "production": 20,
}

# Trusted server-side Tool Risk Registry
TRUSTED_TOOL_REGISTRY: dict[str, ToolRiskProfile] = {
    "query_customer_records": ToolRiskProfile(
        tool_name="query_customer_records",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="read",
        resource_type="customer",
        max_allowed_scope=100,
    ),
    "get_customer": ToolRiskProfile(
        tool_name="get_customer",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="read",
        resource_type="customer",
        max_allowed_scope=1,
    ),
    "get_customer_orders": ToolRiskProfile(
        tool_name="get_customer_orders",
        base_risk=15,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.SENSITIVE,
        operation_type="read",
        resource_type="order",
        max_allowed_scope=100,
    ),
    "get_order": ToolRiskProfile(
        tool_name="get_order",
        base_risk=15,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.SENSITIVE,
        operation_type="read",
        resource_type="order",
        max_allowed_scope=1,
    ),
    "append_customer_audit_note": ToolRiskProfile(
        tool_name="append_customer_audit_note",
        base_risk=20,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="create",
        resource_type="audit_note",
        max_allowed_scope=1,
    ),
    "update_customer": ToolRiskProfile(
        tool_name="update_customer",
        base_risk=25,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="update",
        resource_type="customer",
        max_allowed_scope=1,
    ),
    "delete_customer": ToolRiskProfile(
        tool_name="delete_customer",
        base_risk=30,
        read_only=False,
        destructive=True,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="delete",
        resource_type="customer",
        max_allowed_scope=1,
    ),
    "purge_inactive_customer_data": ToolRiskProfile(
        tool_name="purge_inactive_customer_data",
        base_risk=45,
        read_only=False,
        destructive=True,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="purge",
        resource_type="customer",
        max_allowed_scope=10000,
    ),
    # Canva Remote MCP Tools
    "canva.search_designs": ToolRiskProfile(
        tool_name="canva.search_designs",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="canva_design",
        max_allowed_scope=100,
    ),
    "canva.get_design": ToolRiskProfile(
        tool_name="canva.get_design",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="canva_design",
        max_allowed_scope=1,
    ),
    "canva.create_design": ToolRiskProfile(
        tool_name="canva.create_design",
        base_risk=25,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="write",
        resource_type="canva_design",
        max_allowed_scope=1,
    ),
    "canva.update_design": ToolRiskProfile(
        tool_name="canva.update_design",
        base_risk=35,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="write",
        resource_type="canva_design",
        max_allowed_scope=1,
    ),
    "canva.export_design": ToolRiskProfile(
        tool_name="canva.export_design",
        base_risk=15,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="canva_design",
        max_allowed_scope=1,
    ),
    # GitHub Tools
    "github.get_authenticated_user": ToolRiskProfile(
        tool_name="github.get_authenticated_user",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="github_user",
        max_allowed_scope=1,
    ),
    "github.list_repositories": ToolRiskProfile(
        tool_name="github.list_repositories",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="github_repo",
        max_allowed_scope=100,
    ),
    "github.get_repository": ToolRiskProfile(
        tool_name="github.get_repository",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="github_repo",
        max_allowed_scope=1,
    ),
    "github.list_issues": ToolRiskProfile(
        tool_name="github.list_issues",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="github_issue",
        max_allowed_scope=100,
    ),
    "github.create_issue": ToolRiskProfile(
        tool_name="github.create_issue",
        base_risk=20,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="write",
        resource_type="github_issue",
        max_allowed_scope=1,
    ),
    "github.create_pull_request": ToolRiskProfile(
        tool_name="github.create_pull_request",
        base_risk=35,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="write",
        resource_type="github_pr",
        max_allowed_scope=1,
    ),
    "github.close_issue": ToolRiskProfile(
        tool_name="github.close_issue",
        base_risk=30,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="write",
        resource_type="github_issue",
        max_allowed_scope=1,
    ),
    "github.merge_pull_request": ToolRiskProfile(
        tool_name="github.merge_pull_request",
        base_risk=60,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="merge",
        resource_type="github_pr",
        max_allowed_scope=1,
    ),
    "github.delete_file": ToolRiskProfile(
        tool_name="github.delete_file",
        base_risk=65,
        read_only=False,
        destructive=True,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="delete",
        resource_type="github_file",
        max_allowed_scope=1,
    ),
    "github.delete_repository": ToolRiskProfile(
        tool_name="github.delete_repository",
        base_risk=95,
        read_only=False,
        destructive=True,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="delete",
        resource_type="github_repo",
        max_allowed_scope=1,
    ),
    # Slack Tools
    "slack.search_messages": ToolRiskProfile(
        tool_name="slack.search_messages",
        base_risk=15,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="slack_message",
        max_allowed_scope=100,
    ),
    "slack.read_channel": ToolRiskProfile(
        tool_name="slack.read_channel",
        base_risk=15,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="read",
        resource_type="slack_channel",
        max_allowed_scope=100,
    ),
    "slack.send_message": ToolRiskProfile(
        tool_name="slack.send_message",
        base_risk=35,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="write",
        resource_type="slack_message",
        max_allowed_scope=1,
    ),
    # Google Drive Tools
    "google_drive.search_files": ToolRiskProfile(
        tool_name="google_drive.search_files",
        base_risk=15,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="read",
        resource_type="drive_file",
        max_allowed_scope=100,
    ),
    "google_drive.get_file_metadata": ToolRiskProfile(
        tool_name="google_drive.get_file_metadata",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="read",
        resource_type="drive_file",
        max_allowed_scope=1,
    ),
    "google_drive.create_folder": ToolRiskProfile(
        tool_name="google_drive.create_folder",
        base_risk=20,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.INTERNAL,
        operation_type="write",
        resource_type="drive_file",
        max_allowed_scope=1,
    ),
    "google_drive.delete_file": ToolRiskProfile(
        tool_name="google_drive.delete_file",
        base_risk=50,
        read_only=False,
        destructive=True,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="delete",
        resource_type="drive_file",
        max_allowed_scope=1,
    ),
    # Local Custom MCP Tools
    "custom_mcp.query_customer_records": ToolRiskProfile(
        tool_name="custom_mcp.query_customer_records",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="read",
        resource_type="customer",
        max_allowed_scope=100,
    ),
    "custom_mcp.get_customer": ToolRiskProfile(
        tool_name="custom_mcp.get_customer",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="read",
        resource_type="customer",
        max_allowed_scope=1,
    ),
    "custom_mcp.update_customer": ToolRiskProfile(
        tool_name="custom_mcp.update_customer",
        base_risk=25,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="write",
        resource_type="customer",
        max_allowed_scope=1,
    ),
    "custom_mcp.delete_customer": ToolRiskProfile(
        tool_name="custom_mcp.delete_customer",
        base_risk=50,
        read_only=False,
        destructive=True,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="delete",
        resource_type="customer",
        max_allowed_scope=1,
    ),
    "custom_mcp.purge_inactive_customer_data": ToolRiskProfile(
        tool_name="custom_mcp.purge_inactive_customer_data",
        base_risk=45,
        read_only=False,
        destructive=True,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="purge",
        resource_type="customer",
        max_allowed_scope=10000,
    ),
    "custom_mcp.get_order": ToolRiskProfile(
        tool_name="custom_mcp.get_order",
        base_risk=10,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.SENSITIVE,
        operation_type="read",
        resource_type="order",
        max_allowed_scope=1,
    ),
    "custom_mcp.get_customer_orders": ToolRiskProfile(
        tool_name="custom_mcp.get_customer_orders",
        base_risk=15,
        read_only=True,
        destructive=False,
        external_side_effect=False,
        data_sensitivity=DataSensitivityEnum.SENSITIVE,
        operation_type="read",
        resource_type="order",
        max_allowed_scope=50,
    ),
    "custom_mcp.append_customer_audit_note": ToolRiskProfile(
        tool_name="custom_mcp.append_customer_audit_note",
        base_risk=10,
        read_only=False,
        destructive=False,
        external_side_effect=True,
        data_sensitivity=DataSensitivityEnum.CONFIDENTIAL,
        operation_type="write",
        resource_type="customer",
        max_allowed_scope=1,
    ),
}


def get_tool_profile(tool_name: str) -> Optional[ToolRiskProfile]:
    """
    Retrieves the server-authoritative tool profile from the trusted registry.
    Returns None for unknown tools.
    """
    return TRUSTED_TOOL_REGISTRY.get(tool_name)


def calculate_scale_factor(
    record_count: int,
    bulk_threshold: int = 100,
    critical_threshold: int = 1000,
) -> int:
    """
    Determines scale factor based on the number of records affected.
    Scope escalation is deterministic:
    - 0 or 1 record: 0
    - 2 to bulk_threshold - 1: +5
    - bulk_threshold to critical_threshold - 1: +15
    - >= critical_threshold: +30
    """
    if record_count <= 1:
        return 0
    if record_count < bulk_threshold:
        return 5
    if record_count < critical_threshold:
        return 15
    return 30
